name = "Gophercon"
license = "MIT"
licenselink = "https://github.com/.../.../LICENSE.md"
description = ""
homepage = "http://gopheracademy.com/"
tags = ["", ""]
features = ["", ""]

[author]
  name = ""
  homepage = ""

